---
- name: install pm2
  shell: npm install -g pm2

- name: restart mongodb
  service: name=mongodb state=started
  sudo: yes

- name: start rackhd services
  shell: ~/src/npm/bin/pm2 start ./roles/pm2/files/rackhd.yml
  sudo: yes
