---
- name: create dir /home/vagrant/src/npm
  file: path=/home/vagrant/src/npm state=directory

#- name: change the npm prefix
#  shell: echo prefix=~/src/npm >> ~/.npmrc

- name: install dependency
  apt: pkg={{item}} state=installed
  with_items:
    - g++
    - libkrb5-dev
    - unzip

- name: Npm install Repos
  shell: npm install
  args: 
    chdir: /home/vagrant/src/{{ item }}
  with_items: 
    - on-tasks
    - on-taskgraph
    - on-http
    - on-dhcp-proxy
    - on-tftp
    - on-syslog
    - on-core

- name: install repos link on-core
  shell: npm link /home/vagrant/src/on-core
  args:
    chdir: /home/vagrant/src/{{ item }}
  with_items: 
    - on-tasks
    - on-taskgraph
    - on-http
    - on-dhcp-proxy
    - on-tftp
    - on-syslog

- name: install repos link on-tasks
  shell: npm link /home/vagrant/src/on-tasks
  args:
    chdir: /home/vagrant/src/{{ item }}
  with_items:
    - on-taskgraph
    - on-http
