---

- name: install rackhd
  hosts: nodes
  sudo: yes
  vars:
   github_account: "yaolingling"
  roles:
    - apt
    - build
    - isc-dhcp-server
    - mongodb
    - rabbitmq-server
    - ipmitool
    - snmp
    - configNetwork
    - nodejs
    - cloneCode
    - dependency
    - config_file
    - static_files
    - pm2
